// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL1001Meta contains metadata for rule DL1001.
// Source: hadolint/src/Hadolint/Rule/DL1001.hs
var DL1001Meta = rule.RuleMeta{
	Code:     "DL1001",
	Severity: rule.Ignore,
	Message:  "Please refrain from using inline ignore pragmas                `# hadolint ignore=DLxxxx`.",
}
