// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3052Meta contains metadata for rule DL3052.
// Source: hadolint/src/Hadolint/Rule/DL3052.hs
var DL3052Meta = rule.RuleMeta{
	Code:     "DL3052",
	Severity: rule.Warning,
	Message:  "Label `",
}
