// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3035Meta contains metadata for rule DL3035.
// Source: hadolint/src/Hadolint/Rule/DL3035.hs
var DL3035Meta = rule.RuleMeta{
	Code:     "DL3035",
	Severity: rule.Warning,
	Message:  "Do not use `zypper dist-upgrade`.",
}
