// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3024Meta contains metadata for rule DL3024.
// Source: hadolint/src/Hadolint/Rule/DL3024.hs
var DL3024Meta = rule.RuleMeta{
	Code:     "DL3024",
	Severity: rule.Error,
	Message:  "FROM aliases (stage names) must be unique",
}
