// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3007Meta contains metadata for rule DL3007.
// Source: hadolint/src/Hadolint/Rule/DL3007.hs
var DL3007Meta = rule.RuleMeta{
	Code:     "DL3007",
	Severity: rule.Warning,
	Message:  "Using latest is prone to errors if the image will ever update. Pin the version explicitly       to a release tag",
}
