// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3022Meta contains metadata for rule DL3022.
// Source: hadolint/src/Hadolint/Rule/DL3022.hs
var DL3022Meta = rule.RuleMeta{
	Code:     "DL3022",
	Severity: rule.Warning,
	Message:  "`COPY --from` should reference a previously defined `FROM` alias",
}
