// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3041Meta contains metadata for rule DL3041.
// Source: hadolint/src/Hadolint/Rule/DL3041.hs
var DL3041Meta = rule.RuleMeta{
	Code:     "DL3041",
	Severity: rule.Warning,
	Message:  "Specify version with `dnf install -y <package>-<version>`.",
}
