// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3046Meta contains metadata for rule DL3046.
// Source: hadolint/src/Hadolint/Rule/DL3046.hs
var DL3046Meta = rule.RuleMeta{
	Code:     "DL3046",
	Severity: rule.Warning,
	Message:  "`useradd` without flag `-l` and high UID will result in excessively large Image.",
}
