// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3002Meta contains metadata for rule DL3002.
// Source: hadolint/src/Hadolint/Rule/DL3002.hs
var DL3002Meta = rule.RuleMeta{
	Code:     "DL3002",
	Severity: rule.Warning,
	Message:  "Last USER should not be root",
}
