// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3060Meta contains metadata for rule DL3060.
// Source: hadolint/src/Hadolint/Rule/DL3060.hs
var DL3060Meta = rule.RuleMeta{
	Code:     "DL3060",
	Severity: rule.Info,
	Message:  "`yarn cache clean` missing after `yarn install` was run.",
}
