// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3008Meta contains metadata for rule DL3008.
// Source: hadolint/src/Hadolint/Rule/DL3008.hs
var DL3008Meta = rule.RuleMeta{
	Code:     "DL3008",
	Severity: rule.Warning,
	Message:  "Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get       install <package>=<version>`",
}
