// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3032Meta contains metadata for rule DL3032.
// Source: hadolint/src/Hadolint/Rule/DL3032.hs
var DL3032Meta = rule.RuleMeta{
	Code:     "DL3032",
	Severity: rule.Warning,
	Message:  "`yum clean all` missing after yum command.",
}
