// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.

package rules

import "github.com/forkcloser/godolint/internal/rule"

// DL3066Meta contains metadata for rule DL3066.
// Source: hadolint/src/Hadolint/Rule/DL3066.hs
var DL3066Meta = rule.Meta{
	Code:     "DL3066",
	Severity: rule.Info,
	Message:  "Non-numeric user-id may not be resolvable by host system",
}
