// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3055Meta contains metadata for rule DL3055.
// Source: hadolint/src/Hadolint/Rule/DL3055.hs
var DL3055Meta = rule.RuleMeta{
	Code:     "DL3055",
	Severity: rule.Warning,
	Message:  "Label `",
}
