// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3049Meta contains metadata for rule DL3049.
// Source: hadolint/src/Hadolint/Rule/DL3049.hs
var DL3049Meta = rule.RuleMeta{
	Code:     "DL3049",
	Severity: rule.Info,
	Message:  "Label `",
}
