// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3019Meta contains metadata for rule DL3019.
// Source: hadolint/src/Hadolint/Rule/DL3019.hs
var DL3019Meta = rule.RuleMeta{
	Code:     "DL3019",
	Severity: rule.Info,
	Message:  "Use the `--no-cache` switch to avoid the need to use `--update` and       remove `/var/cache/apk/*` when done installing packages",
}
