// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3043Meta contains metadata for rule DL3043.
// Source: hadolint/src/Hadolint/Rule/DL3043.hs
var DL3043Meta = rule.RuleMeta{
	Code:     "DL3043",
	Severity: rule.Error,
	Message:  "`ONBUILD`, `FROM` or `MAINTAINER` triggered from within `ONBUILD` instruction.",
}
