// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3028Meta contains metadata for rule DL3028.
// Source: hadolint/src/Hadolint/Rule/DL3028.hs
var DL3028Meta = rule.RuleMeta{
	Code:     "DL3028",
	Severity: rule.Warning,
	Message:  "Pin versions in gem install. Instead of `gem install <gem>` use `gem       install <gem>:<version>`",
}
