// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3010Meta contains metadata for rule DL3010.
// Source: hadolint/src/Hadolint/Rule/DL3010.hs
var DL3010Meta = rule.RuleMeta{
	Code:     "DL3010",
	Severity: rule.Info,
	Message:  "Use `ADD` for extracting archives into an image",
}
