// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3036Meta contains metadata for rule DL3036.
// Source: hadolint/src/Hadolint/Rule/DL3036.hs
var DL3036Meta = rule.RuleMeta{
	Code:     "DL3036",
	Severity: rule.Warning,
	Message:  "`zypper clean` missing after zypper use.",
}
