// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3057Meta contains metadata for rule DL3057.
// Source: hadolint/src/Hadolint/Rule/DL3057.hs
var DL3057Meta = rule.RuleMeta{
	Code:     "DL3057",
	Severity: rule.Warning,
	Message:  "`HEALTHCHECK` instruction missing.",
}
