// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3047Meta contains metadata for rule DL3047.
// Source: hadolint/src/Hadolint/Rule/DL3047.hs
var DL3047Meta = rule.RuleMeta{
	Code:     "DL3047",
	Severity: rule.Info,
	Message:  "Avoid use of wget without progress bar. Use `wget --progress=dot:giga <url>`.       Or consider using `-q` or `-nv` (shorthands for `--quiet` or `--no-verbose`).",
}
