// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3037Meta contains metadata for rule DL3037.
// Source: hadolint/src/Hadolint/Rule/DL3037.hs
var DL3037Meta = rule.RuleMeta{
	Code:     "DL3037",
	Severity: rule.Warning,
	Message:  "Specify version with `zypper install -y <package>=<version>`.",
}
