// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.

package rules

import "github.com/forkcloser/godolint/internal/rule"

// DL3067Meta contains metadata for rule DL3067.
// Source: hadolint/src/Hadolint/Rule/DL3067.hs
var DL3067Meta = rule.Meta{
	Code:     "DL3067",
	Severity: rule.Warning,
	Message:  "Do not copy an entire filesystem from another stage",
}
