// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3020Meta contains metadata for rule DL3020.
// Source: hadolint/src/Hadolint/Rule/DL3020.hs
var DL3020Meta = rule.RuleMeta{
	Code:     "DL3020",
	Severity: rule.Error,
	Message:  "Use COPY instead of ADD for files and folders",
}
