// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3038Meta contains metadata for rule DL3038.
// Source: hadolint/src/Hadolint/Rule/DL3038.hs
var DL3038Meta = rule.RuleMeta{
	Code:     "DL3038",
	Severity: rule.Warning,
	Message:  "Use the -y switch to avoid manual input `dnf install -y <package>`",
}
