// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3044Meta contains metadata for rule DL3044.
// Source: hadolint/src/Hadolint/Rule/DL3044.hs
var DL3044Meta = rule.RuleMeta{
	Code:     "DL3044",
	Severity: rule.Error,
	Message:  "Do not refer to an environment variable within the same `ENV` statement where it is defined.",
}
