// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3040Meta contains metadata for rule DL3040.
// Source: hadolint/src/Hadolint/Rule/DL3040.hs
var DL3040Meta = rule.RuleMeta{
	Code:     "DL3040",
	Severity: rule.Warning,
	Message:  "`dnf clean all` missing after dnf command.",
}
