// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.

package rules

import "github.com/forkcloser/godolint/internal/rule"

// DL3050Meta contains metadata for rule DL3050.
// Source: hadolint/src/Hadolint/Rule/DL3050.hs
var DL3050Meta = rule.Meta{
	Code:     "DL3050",
	Severity: rule.Info,
	Message:  "Superfluous label(s) present.",
}
