// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3059Meta contains metadata for rule DL3059.
// Source: hadolint/src/Hadolint/Rule/DL3059.hs
var DL3059Meta = rule.RuleMeta{
	Code:     "DL3059",
	Severity: rule.Info,
	Message:  "Multiple consecutive `RUN` instructions. Consider consolidation.",
}
