// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3001Meta contains metadata for rule DL3001.
// Source: hadolint/src/Hadolint/Rule/DL3001.hs
var DL3001Meta = rule.RuleMeta{
	Code:     "DL3001",
	Severity: rule.Info,
	Message:  "For some bash commands it makes no sense running them in a Docker container like `ssh`,       `vim`, `shutdown`, `service`, `ps`, `free`, `top`, `kill`, `mount`, `ifconfig`",
}
