// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3013Meta contains metadata for rule DL3013.
// Source: hadolint/src/Hadolint/Rule/DL3013.hs
var DL3013Meta = rule.RuleMeta{
	Code:     "DL3013",
	Severity: rule.Warning,
	Message:  "Pin versions in pip. Instead of `pip install <package>` use `pip install       <package>==<version>` or `pip install --requirement <requirements file>`",
}
