// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.

package rules

import "github.com/forkcloser/godolint/internal/rule"

// DL3064Meta contains metadata for rule DL3064.
// Source: hadolint/src/Hadolint/Rule/DL3064.hs
var DL3064Meta = rule.Meta{
	Code:     "DL3064",
	Severity: rule.Warning,
	Message:  "Potentially sensitive data should not be used in the `ARG` or `ENV` commands",
}
