// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3023Meta contains metadata for rule DL3023.
// Source: hadolint/src/Hadolint/Rule/DL3023.hs
var DL3023Meta = rule.RuleMeta{
	Code:     "DL3023",
	Severity: rule.Error,
	Message:  "`COPY --from` cannot reference its own `FROM` alias",
}
