// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3014Meta contains metadata for rule DL3014.
// Source: hadolint/src/Hadolint/Rule/DL3014.hs
var DL3014Meta = rule.RuleMeta{
	Code:     "DL3014",
	Severity: rule.Warning,
	Message:  "Use the `-y` switch to avoid manual input `apt-get -y install <package>`",
}
