// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3018Meta contains metadata for rule DL3018.
// Source: hadolint/src/Hadolint/Rule/DL3018.hs
var DL3018Meta = rule.RuleMeta{
	Code:     "DL3018",
	Severity: rule.Warning,
	Message:  "Pin versions in apk add. Instead of `apk add <package>`       use `apk add <package>=<version>`",
}
