// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3006Meta contains metadata for rule DL3006.
// Source: hadolint/src/Hadolint/Rule/DL3006.hs
var DL3006Meta = rule.RuleMeta{
	Code:     "DL3006",
	Severity: rule.Warning,
	Message:  "Always tag the version of an image explicitly",
}
