// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3048Meta contains metadata for rule DL3048.
// Source: hadolint/src/Hadolint/Rule/DL3048.hs
var DL3048Meta = rule.RuleMeta{
	Code:     "DL3048",
	Severity: rule.Style,
	Message:  "Invalid label key.",
}
