// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3026Meta contains metadata for rule DL3026.
// Source: hadolint/src/Hadolint/Rule/DL3026.hs
var DL3026Meta = rule.RuleMeta{
	Code:     "DL3026",
	Severity: rule.Error,
	Message:  "Use only an allowed registry in the FROM image",
}
