// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3025Meta contains metadata for rule DL3025.
// Source: hadolint/src/Hadolint/Rule/DL3025.hs
var DL3025Meta = rule.RuleMeta{
	Code:     "DL3025",
	Severity: rule.Warning,
	Message:  "Use arguments JSON notation for CMD and ENTRYPOINT arguments",
}
