// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3033Meta contains metadata for rule DL3033.
// Source: hadolint/src/Hadolint/Rule/DL3033.hs
var DL3033Meta = rule.RuleMeta{
	Code:     "DL3033",
	Severity: rule.Warning,
	Message:  "Specify version with `yum install -y <package>-<version>`.",
}
