// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3062Meta contains metadata for rule DL3062.
// Source: hadolint/src/Hadolint/Rule/DL3062.hs
var DL3062Meta = rule.RuleMeta{
	Code:     "DL3062",
	Severity: rule.Warning,
	Message:  "Pin versions in go. Instead of `go install <package>` use `go install <package>@<version>`",
}
