// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3058Meta contains metadata for rule DL3058.
// Source: hadolint/src/Hadolint/Rule/DL3058.hs
var DL3058Meta = rule.RuleMeta{
	Code:     "DL3058",
	Severity: rule.Warning,
	Message:  "Label `",
}
