// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3016Meta contains metadata for rule DL3016.
// Source: hadolint/src/Hadolint/Rule/DL3016.hs
var DL3016Meta = rule.RuleMeta{
	Code:     "DL3016",
	Severity: rule.Warning,
	Message:  "Pin versions in npm. Instead of `npm install <package>` use `npm install       <package>@<version>`",
}
