// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3004Meta contains metadata for rule DL3004.
// Source: hadolint/src/Hadolint/Rule/DL3004.hs
var DL3004Meta = rule.RuleMeta{
	Code:     "DL3004",
	Severity: rule.Error,
	Message:  "Do not use sudo as it leads to unpredictable behavior. Use a tool like       gosu to enforce root",
}
