// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3029Meta contains metadata for rule DL3029.
// Source: hadolint/src/Hadolint/Rule/DL3029.hs
var DL3029Meta = rule.RuleMeta{
	Code:     "DL3029",
	Severity: rule.Warning,
	Message:  "Do not use --platform flag with FROM",
}
