// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.

package rules

import "github.com/forkcloser/godolint/internal/rule"

// DL3065Meta contains metadata for rule DL3065.
// Source: hadolint/src/Hadolint/Rule/DL3065.hs
var DL3065Meta = rule.Meta{
	Code:     "DL3065",
	Severity: rule.Warning,
	Message:  "Setting `FROM --platform` to predefined `$TARGETPLATFORM` in is redundant as this is the default behavior",
}
