// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3034Meta contains metadata for rule DL3034.
// Source: hadolint/src/Hadolint/Rule/DL3034.hs
var DL3034Meta = rule.RuleMeta{
	Code:     "DL3034",
	Severity: rule.Warning,
	Message:  "Non-interactive switch missing from `zypper` command: `zypper install -y`",
}
