// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.

package rules

import "github.com/forkcloser/godolint/internal/rule"

// DL3063Meta contains metadata for rule DL3063.
// Source: hadolint/src/Hadolint/Rule/DL3063.hs
var DL3063Meta = rule.Meta{
	Code:     "DL3063",
	Severity: rule.Warning,
	Message:  "stage name should not be a reserved word",
}
