// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3021Meta contains metadata for rule DL3021.
// Source: hadolint/src/Hadolint/Rule/DL3021.hs
var DL3021Meta = rule.RuleMeta{
	Code:     "DL3021",
	Severity: rule.Error,
	Message:  "COPY with more than 2 arguments requires the last argument to end with /",
}
