// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3061Meta contains metadata for rule DL3061.
// Source: hadolint/src/Hadolint/Rule/DL3061.hs
var DL3061Meta = rule.RuleMeta{
	Code:     "DL3061",
	Severity: rule.Error,
	Message:  "Invalid instruction order. Dockerfile must begin with `FROM`,               `ARG` or comment.",
}
