// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3053Meta contains metadata for rule DL3053.
// Source: hadolint/src/Hadolint/Rule/DL3053.hs
var DL3053Meta = rule.RuleMeta{
	Code:     "DL3053",
	Severity: rule.Warning,
	Message:  "Label `",
}
