// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.

package rules

import "github.com/forkcloser/godolint/internal/rule"

// DL3056Meta contains metadata for rule DL3056.
// Source: hadolint/src/Hadolint/Rule/DL3056.hs
var DL3056Meta = rule.Meta{
	Code:     "DL3056",
	Severity: rule.Warning,
	Message:  "Label `",
}
