// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3000Meta contains metadata for rule DL3000.
// Source: hadolint/src/Hadolint/Rule/DL3000.hs
var DL3000Meta = rule.RuleMeta{
	Code:     "DL3000",
	Severity: rule.Error,
	Message:  "Use absolute WORKDIR",
}
