// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3003Meta contains metadata for rule DL3003.
// Source: hadolint/src/Hadolint/Rule/DL3003.hs
var DL3003Meta = rule.RuleMeta{
	Code:     "DL3003",
	Severity: rule.Warning,
	Message:  "Use WORKDIR to switch to a directory",
}
