// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3042Meta contains metadata for rule DL3042.
// Source: hadolint/src/Hadolint/Rule/DL3042.hs
var DL3042Meta = rule.RuleMeta{
	Code:     "DL3042",
	Severity: rule.Warning,
	Message:  "Avoid use of cache directory with pip.               Use `pip install --no-cache-dir <package>`",
}
