// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3051Meta contains metadata for rule DL3051.
// Source: hadolint/src/Hadolint/Rule/DL3051.hs
var DL3051Meta = rule.RuleMeta{
	Code:     "DL3051",
	Severity: rule.Warning,
	Message:  "label `",
}
