// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3009Meta contains metadata for rule DL3009.
// Source: hadolint/src/Hadolint/Rule/DL3009.hs
var DL3009Meta = rule.RuleMeta{
	Code:     "DL3009",
	Severity: rule.Info,
	Message:  "Delete the apt lists (/var/lib/apt/lists) after installing something",
}
