// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3012Meta contains metadata for rule DL3012.
// Source: hadolint/src/Hadolint/Rule/DL3012.hs
var DL3012Meta = rule.RuleMeta{
	Code:     "DL3012",
	Severity: rule.Error,
	Message:  "Multiple `HEALTHCHECK` instructions",
}
