// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3045Meta contains metadata for rule DL3045.
// Source: hadolint/src/Hadolint/Rule/DL3045.hs
var DL3045Meta = rule.RuleMeta{
	Code:     "DL3045",
	Severity: rule.Warning,
	Message:  "`COPY` to a relative destination without `WORKDIR` set.",
}
