// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3027Meta contains metadata for rule DL3027.
// Source: hadolint/src/Hadolint/Rule/DL3027.hs
var DL3027Meta = rule.RuleMeta{
	Code:     "DL3027",
	Severity: rule.Warning,
	Message:  "Do not use apt as it is meant to be an end-user tool, use apt-get               or apt-cache instead",
}
