// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3054Meta contains metadata for rule DL3054.
// Source: hadolint/src/Hadolint/Rule/DL3054.hs
var DL3054Meta = rule.RuleMeta{
	Code:     "DL3054",
	Severity: rule.Warning,
	Message:  "Label `",
}
