// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3015Meta contains metadata for rule DL3015.
// Source: hadolint/src/Hadolint/Rule/DL3015.hs
var DL3015Meta = rule.RuleMeta{
	Code:     "DL3015",
	Severity: rule.Info,
	Message:  "Avoid additional packages by specifying `--no-install-recommends`",
}
