// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL3011Meta contains metadata for rule DL3011.
// Source: hadolint/src/Hadolint/Rule/DL3011.hs
var DL3011Meta = rule.RuleMeta{
	Code:     "DL3011",
	Severity: rule.Error,
	Message:  "Valid UNIX ports range from 0 to 65535",
}
