// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL4005Meta contains metadata for rule DL4005.
// Source: hadolint/src/Hadolint/Rule/DL4005.hs
var DL4005Meta = rule.RuleMeta{
	Code:     "DL4005",
	Severity: rule.Warning,
	Message:  "Use SHELL to change the default shell",
}
