// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL4001Meta contains metadata for rule DL4001.
// Source: hadolint/src/Hadolint/Rule/DL4001.hs
var DL4001Meta = rule.RuleMeta{
	Code:     "DL4001",
	Severity: rule.Warning,
	Message:  "Either use Wget or Curl but not both",
}
