// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL4006Meta contains metadata for rule DL4006.
// Source: hadolint/src/Hadolint/Rule/DL4006.hs
var DL4006Meta = rule.RuleMeta{
	Code:     "DL4006",
	Severity: rule.Warning,
	Message:  "Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using       /bin/sh in an alpine image or if your shell is symlinked to busybox then consider       explicitly setting your SHELL to /bin/ash, or disable this check",
}
