// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL4003Meta contains metadata for rule DL4003.
// Source: hadolint/src/Hadolint/Rule/DL4003.hs
var DL4003Meta = rule.RuleMeta{
	Code:     "DL4003",
	Severity: rule.Warning,
	Message:  "Multiple `CMD` instructions found. If you list more than one `CMD` then only the last       `CMD` will take effect",
}
