// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL4004Meta contains metadata for rule DL4004.
// Source: hadolint/src/Hadolint/Rule/DL4004.hs
var DL4004Meta = rule.RuleMeta{
	Code:     "DL4004",
	Severity: rule.Error,
	Message:  "Multiple `ENTRYPOINT` instructions found. If you list more than one `ENTRYPOINT` then       only the last `ENTRYPOINT` will take effect",
}
