// Code generated by go generate; DO NOT EDIT.
// This file is auto-generated from hadolint rules.
package rules

import "github.com/farcloser/godolint/internal/rule"

// DL4000Meta contains metadata for rule DL4000.
// Source: hadolint/src/Hadolint/Rule/DL4000.hs
var DL4000Meta = rule.RuleMeta{
	Code:     "DL4000",
	Severity: rule.Error,
	Message:  "MAINTAINER is deprecated",
}
